# build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/examples/dispatcher

RUN go build -o server main.go

# runtime stage
FROM alpine:3.18

WORKDIR /app
COPY --from=builder /app/examples/dispatcher/server .

EXPOSE 8080
CMD ["/app/server"]
